services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guestbook}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-main}
      POSTGRES_USER: ${POSTGRES_USER:-main}
    ports:
      - "5432:5432" # Mapowanie portu hosta na port kontenera
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-guestbook}", "-U", "${POSTGRES_USER:-main}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
