<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506091450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conference_speaker (conference_id INT NOT NULL, speaker_id INT NOT NULL, PRIMARY KEY (conference_id, speaker_id))');
        $this->addSql('CREATE INDEX IDX_807844D9604B8382 ON conference_speaker (conference_id)');
        $this->addSql('CREATE INDEX IDX_807844D9D04A0F27 ON conference_speaker (speaker_id)');
        $this->addSql('CREATE TABLE speaker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, bio TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE conference_speaker ADD CONSTRAINT FK_807844D9604B8382 FOREIGN KEY (conference_id) REFERENCES conference (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conference_speaker ADD CONSTRAINT FK_807844D9D04A0F27 FOREIGN KEY (speaker_id) REFERENCES speaker (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conference_speaker DROP CONSTRAINT FK_807844D9604B8382');
        $this->addSql('ALTER TABLE conference_speaker DROP CONSTRAINT FK_807844D9D04A0F27');
        $this->addSql('DROP TABLE conference_speaker');
        $this->addSql('DROP TABLE speaker');
    }
}
